name: Setup
runs:
  using: composite
  steps:
    - name: Setup Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Setup Just
      uses: extractions/setup-just@v1
      with:
        just-version: 1.5.0
