version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
changelog:
  disable: true

brews:
  - name: supersim
    directory: Formula
    homepage: "https://github.com/ethereum-optimism/supersim"
    description: "Supersim is a local dev environment for the Superchain"
    repository:
      owner: ethereum-optimism
      name: homebrew-tap
      token: "{{ .Env.TAP_REPO_GITHUB_TOKEN }}"