name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
  merge_group:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FOUNDRY_PROFILE: ci

jobs:
  contracts-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Forge build
        run: |
          just build-contracts
        id: build

      - name: Run Forge tests
        run: |
          just test-contracts
        id: test
  
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      
      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          args: --timeout=5m

      - name: Install dependencies
        run: go mod download

      - name: Run linter
        run: just lint-go

  go-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      
      - name: Setup
        uses: ./.github/actions/setup

      - name: Install dependencies
        run: go mod download

      - name: Set environment variables from secrets
        run: |
          echo "SUPERSIM_RPC_URL_OP=$SUPERSIM_RPC_URL_OP" >> .env
          echo "SUPERSIM_RPC_URL_BASE=$SUPERSIM_RPC_URL_BASE" >> .env
        env:
          SUPERSIM_RPC_URL_OP: ${{ secrets.SUPERSIM_RPC_URL_OP }}
          SUPERSIM_RPC_URL_BASE: ${{ secrets.SUPERSIM_RPC_URL_BASE }}

      - name: Run tests
        run: just test-go
